// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates the user the based on the credentials and returns a token which will be used to authorize requests as a bearer token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Authenticate a user",
                "parameters": [
                    {
                        "description": "Username",
                        "name": "username",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Password",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Student ID",
                        "name": "studentId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/knust-server-status": {
            "get": {
                "description": "This checks which of the used KNUST servers are up or down",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KNUST Servers"
                ],
                "summary": "Get the status of KNUST servers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KNUSTServerStatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/knust-server-status/badge": {
            "get": {
                "description": "This sums up the status of the servers and returns an SVG badge as a summary from shields.io",
                "tags": [
                    "KNUST Servers"
                ],
                "summary": "Get the status of KNUST servers as a badge",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/news": {
            "get": {
                "description": "Returns the latest news available",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News"
                ],
                "summary": "Get latest news",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.NewsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/news/{slug}": {
            "get": {
                "description": "Get the post details of the news based on the slug",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News"
                ],
                "summary": "Get news post details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "News slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.NewsDetailsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "description": "Returns personal, programme and contact user data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User Data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserDataResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/image/{studentId}": {
            "get": {
                "description": "Serves up the user image based on the student id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "studentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/results": {
            "post": {
                "description": "Returns results for the selected academic year and semester",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Results"
                ],
                "summary": "Get results",
                "parameters": [
                    {
                        "description": "Year",
                        "name": "year",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Sem",
                        "name": "sem",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetResultsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/results/selection": {
            "get": {
                "description": "Returns a list of years and semester that the results are available for",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Results"
                ],
                "summary": "Get available results",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResultsSelectionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ContactUserData": {
            "type": "object",
            "properties": {
                "alt_personal_mobile": {
                    "type": "string"
                },
                "knust_mobile": {
                    "type": "string"
                },
                "personal_email": {
                    "type": "string"
                },
                "personal_mobile": {
                    "type": "string"
                },
                "postal_address": {
                    "type": "string"
                },
                "residential_address": {
                    "type": "string"
                },
                "school_email": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.GetResultsResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "personal_data": {
                    "$ref": "#/definitions/models.ResultsPersonalData"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Results"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/models.ResultsSummary"
                },
                "trails": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.KNUSTServer": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.KNUSTServerStatusResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "servers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.KNUSTServer"
                    }
                }
            }
        },
        "models.News": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.NewsDetails": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NewsDetailsContent"
                    }
                },
                "date": {
                    "type": "string"
                },
                "featured_image": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "tile": {
                    "type": "string"
                }
            }
        },
        "models.NewsDetailsContent": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.NewsDetailsResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "news": {
                    "$ref": "#/definitions/models.NewsDetails"
                }
            }
        },
        "models.NewsResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "news": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.News"
                    }
                }
            }
        },
        "models.PersonalUserData": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "other_names": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "religion": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.ProgrammeUserData": {
            "type": "object",
            "properties": {
                "indexNo": {
                    "type": "string"
                },
                "programme_stream": {
                    "type": "string"
                },
                "studentId": {
                    "type": "string"
                }
            }
        },
        "models.Results": {
            "type": "object",
            "properties": {
                "course_code": {
                    "type": "string"
                },
                "course_name": {
                    "type": "string"
                },
                "credits": {
                    "type": "string"
                },
                "grade": {
                    "type": "string"
                },
                "total_mark": {
                    "type": "string"
                }
            }
        },
        "models.ResultsPersonalData": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "indexNo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "option": {
                    "type": "string"
                },
                "programme": {
                    "type": "string"
                },
                "studentId": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "models.ResultsSelection": {
            "type": "object",
            "properties": {
                "sems": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "years": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.ResultsSelectionResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "results": {
                    "$ref": "#/definitions/models.ResultsSelection"
                }
            }
        },
        "models.ResultsSummary": {
            "type": "object",
            "properties": {
                "credits_calculated": {
                    "$ref": "#/definitions/models.ResultsSummaryExtra"
                },
                "credits_obtained": {
                    "$ref": "#/definitions/models.ResultsSummaryExtra"
                },
                "credits_registered": {
                    "$ref": "#/definitions/models.ResultsSummaryExtra"
                },
                "cwa": {
                    "$ref": "#/definitions/models.ResultsSummaryExtra"
                },
                "weighted_marks": {
                    "$ref": "#/definitions/models.ResultsSummaryExtra"
                }
            }
        },
        "models.ResultsSummaryExtra": {
            "type": "object",
            "properties": {
                "cumulative": {
                    "type": "string"
                },
                "semester": {
                    "type": "string"
                }
            }
        },
        "models.UserData": {
            "type": "object",
            "properties": {
                "contact": {
                    "$ref": "#/definitions/models.ContactUserData"
                },
                "personal": {
                    "$ref": "#/definitions/models.PersonalUserData"
                },
                "programme": {
                    "$ref": "#/definitions/models.ProgrammeUserData"
                }
            }
        },
        "models.UserDataResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "user_data": {
                    "$ref": "#/definitions/models.UserData"
                }
            }
        },
        "models.UserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
